### ISSUE TITLE
Impossible to add technology to a new Entity

### ISSUE THREAD

**Issue by ylegros** [axa-group/radar#88]
**Describe the bug**
Impossible to add technology to a new Entity

**To Reproduce**
1. Add an entity
2. Add an admin to this entity
3. login with this admin
4. Try to add a technology

**Expected behavior**
Technology Added

**Screenshots**
loading infinitely

![image](https://user-images.githubusercontent.com/3329118/66112067-b7d1a580-e5fc-11e9-9788-c8efb12f6808.png)

Stack trace : 

System.NullReferenceException: Object reference not set to an instance of an object.
   at RadarTechno.Entities.EntityRepository.AddTechnology(EntityTechnology entityTechnology, String id, ITechnologyRepository technologyRepository) in /src/src/RadarTechno/Entities/EntityRepository.cs:line 101
   at RadarTechno.Entities.EntityController.AddTechnology(IEntityRepository entityRepository, IQueue queue, ITechnologyRepository technologyRepository, EntityTechnology entityTechnology, String id) in /src/src/RadarTechno/Entities/EntityController.cs:line 186
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at NSwag.AspNetCore.Middlewares.SwaggerUiIndexMiddleware`1.Invoke(HttpContext context)
   at NSwag.AspNetCore.Middlewares.RedirectToIndexMiddleware.Invoke(HttpContext context)
   at NSwag.AspNetCore.Middlewares.SwaggerDocumentMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)

**Desktop (please complete the following information):**
 - Browser chrome
 - Version 76.0.3809.132 (Official Build) (64-bit)

**Comment by guillaumechervetaxa** [comment]
Thank you @ylegros , it has been fixed by @bernard-arnaud !
